name: gazap
description: "Mon gaz."

publish_to: 'none' # Pour indiquer que ce projet n'est pas destiné à pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

assets:
  - assets/  # Assurez-vous que le dossier images existe dans assets
# - assets/icons/   # Assurez-vous que le dossier icons existe dans assets

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
