name: gazap
description: "Mon gaz à moi" # Description du projet

publish_to: 'none' # Pour indiquer que ce projet n'est pas destiné à pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  flutter_rating_bar: ^4.0.0  # rating_bar for feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  
    - assets/icons/   

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Bold.ttf
        - asset: fonts/Inter_24pt-Medium.ttf
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_24pt-SemiBold.ttf
          weight: 700
